-- ============================================================================
-- mini-crm — RECONSTRUCTED SCHEMA
-- ============================================================================
-- Generated by reading every route/server file that touches the database
-- (no migration file / ORM ever existed — schema was applied ad-hoc via SSH
-- and lost when the production DB was deleted). This file is a best-effort
-- reconstruction from actual SQL usage (SELECT/INSERT/UPDATE column lists,
-- WHERE/ORDER BY/JOIN patterns) plus src/lib/types.ts as corroborating
-- evidence. Statements marked "-- GUESS:" were not directly provable from
-- a query and should be double-checked against any surviving backup/dump
-- before being trusted blindly.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gen_random_uuid() (native since PG13, kept for safety on older instances)

-- ----------------------------------------------------------------------------
-- ENUM TYPES
-- ----------------------------------------------------------------------------

-- Values confirmed by src/lib/components/TimelineItem.svelte iconMap/colorMap keys
-- (telefonat, besuch, notiz, meeting, whatsapp, wechat, linkedin, signal, sonstiges)
-- and matches the pre-existing V1 schema description.
CREATE TYPE interaction_typ AS ENUM (
  'telefonat', 'besuch', 'notiz', 'meeting', 'whatsapp', 'wechat', 'linkedin', 'signal', 'sonstiges'
);

-- Confirmed: src/lib/types.ts Email.richtung, TimelineItem.svelte 'rein'/'raus' keys,
-- and contact_timeline usage (SELECT richtung as subtyp FROM emails).
CREATE TYPE email_richtung AS ENUM ('rein', 'raus');

-- Confirmed: WHERE a.status = 'offen', CASE WHEN status='offen' THEN 'erledigt' ELSE 'offen' END
-- across actions/+page.server.ts and contacts/[id]/+page.server.ts.
CREATE TYPE action_status AS ENUM ('offen', 'erledigt');

-- GUESS: values are taken from src/lib/types.ts `ProspectStatus` union and from the
-- default fallback 'gesendet' used in prospects/+page.server.ts create/update actions.
-- No query ever casts or constrains this value against a fixed list at the DB level,
-- and api/v1/prospects/+server.ts happily inserts an explicit NULL for status, so the
-- column must be NULLable. It is plausible this was actually a plain TEXT column in
-- production rather than a real Postgres ENUM — verify before relying on strict
-- enum enforcement (an ENUM would reject unexpected values that a plain text column
-- would silently accept, e.g. legacy/typo'd status strings from CSV imports).
CREATE TYPE prospect_status AS ENUM (
  'gesendet', 'geantwortet', 'termin', 'kein_interesse', 'bounce', 'abgesagt'
);

-- ----------------------------------------------------------------------------
-- companies
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT/UPDATE column lists in:
--   src/routes/companies/+page.server.ts (create/update)
--   src/routes/companies/[id]/+page.server.ts (update)
--   src/routes/api/v1/companies/+server.ts (POST/PATCH)
-- and src/lib/types.ts `Company`.
CREATE TABLE companies (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text NOT NULL,                 -- always present in every INSERT; required client-side too
  website    text,
  strasse    text,
  plz        text,
  ort        text,
  land       text,
  notizen    text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- GUESS: no explicit UNIQUE constraint is provable — api/v1/companies/+server.ts POST
-- only does an application-level "SELECT id FROM companies WHERE name ILIKE $name"
-- de-dupe check before inserting, which would be redundant/racy if a DB constraint
-- already enforced uniqueness. Left as a plain index for search performance, NOT unique.
CREATE INDEX idx_companies_name ON companies (lower(name));

-- ----------------------------------------------------------------------------
-- contacts
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT/UPDATE column lists in:
--   src/routes/contacts/+page.server.ts (create/update — extractContactFields)
--   src/routes/api/v1/contacts/+server.ts (POST/PATCH)
--   src/routes/contacts/[id]/+page.server.ts (update_contact)
--   src/routes/api/contacts/[id]/photo/+server.ts (photo only)
-- and src/lib/types.ts `Contact`.
CREATE TABLE contacts (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    uuid REFERENCES companies(id) ON DELETE SET NULL,
  name          text NOT NULL,               -- always present; falls back to 'Unbekannt' in app code
  vorname       text,
  nachname      text,
  titel         text,
  -- GUESS: TS type restricts to 'Herr' | 'Frau' | null (src/lib/types.ts), but no query
  -- enforces this at the DB level (plain string interpolation in every INSERT/UPDATE).
  -- Modeled as TEXT rather than an ENUM to avoid rejecting legacy/blank values; tighten
  -- to an enum later if a real backup confirms only these two values were ever stored.
  anrede        text,
  strasse       text,
  plz           text,
  ort           text,
  -- GUESS: treated as DATE (birthday, no time-of-day semantics observed). Only ever
  -- passed through as a raw form string (d.get('geburtstag')) — no date-math or
  -- comparison operators seen in any query, so DATE vs TEXT is inferred, not proven.
  geburtstag    date,
  email         text,
  telefon       text,
  telefon2      text,
  whatsapp      text,
  wechat_id     text,
  linkedin_url  text,
  rolle         text,
  notizen       text,
  -- GUESS: only ever written via api/contacts/[id]/photo/+server.ts as a base64 data
  -- URL string (`data:${mediaType};base64,${base64}`), never part of the main
  -- contact create/update INSERTs — so no NOT NULL/default, nullable text blob.
  photo         text,
  -- Confirmed as text[]: COALESCE(c.tags, '{}'::text[]) and `${tag} = ANY(c.tags)` /
  -- `unnest(tags)` appear throughout (e.g. src/routes/+page.server.ts, contacts/+page.server.ts).
  tags          text[] NOT NULL DEFAULT '{}',
  iban          text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_contacts_company_id ON contacts (company_id);
CREATE INDEX idx_contacts_tags ON contacts USING GIN (tags);
CREATE INDEX idx_contacts_name ON contacts (lower(name));
CREATE INDEX idx_contacts_email ON contacts (lower(email));

-- ----------------------------------------------------------------------------
-- interactions
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT in contacts/[id]/+page.server.ts (add_interaction)
-- and UPDATE in (update_interaction): zusammenfassung, text.
CREATE TABLE interactions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id      uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  typ             interaction_typ NOT NULL,
  datum           timestamptz NOT NULL DEFAULT now(), -- add_interaction passes 'now()' literal as fallback
  zusammenfassung text,
  text            text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_interactions_contact_id_datum ON interactions (contact_id, datum DESC);

-- ----------------------------------------------------------------------------
-- emails
-- ----------------------------------------------------------------------------
-- Columns contact_id/richtung/von/an/betreff/body_text/datum confirmed via INSERT
-- in contacts/[id]/+page.server.ts (add_email) and UPDATE (update_email: betreff,
-- body_text). cc/body_html/gmail_thread_id/gmail_message_id have NO INSERT/UPDATE
-- evidence anywhere in the routes read — they only appear in src/lib/types.ts and
-- in the pre-existing V1 schema description, implying they were populated by an
-- external Gmail-sync process not present in this repo (or a feature that was
-- removed). Kept in the table per that evidence but flagged.
CREATE TABLE emails (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Nullable per src/lib/types.ts (`contact_id: string | null`) even though the only
  -- in-app INSERT path (add_email) always supplies params.id — likely nullable to
  -- support inbox emails not yet matched to a contact via an external sync.
  contact_id        uuid REFERENCES contacts(id) ON DELETE SET NULL,
  richtung          email_richtung NOT NULL,
  -- GUESS: no query ever reads/writes gmail_thread_id or gmail_message_id — carried
  -- over from the known V1 schema + types.ts only. UNIQUE on gmail_message_id kept
  -- from V1 but unverified against any live query in this codebase.
  gmail_thread_id   text,
  gmail_message_id  text UNIQUE,
  von               text,
  an                text,
  betreff           text, -- FIX: confirmed via add_email/update_email INSERT+UPDATE column lists, was dropped from the original generated DDL by mistake.
  -- GUESS: cc — same as above, present only in types.ts, never read/written in code.
  cc                text,
  -- GUESS: body_html — same as above, present only in types.ts, never read/written in code.
  body_html         text,
  body_text         text,
  datum             timestamptz NOT NULL DEFAULT now(), -- add_email passes 'now()' literal as fallback
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_emails_contact_id_datum ON emails (contact_id, datum DESC);
CREATE INDEX idx_emails_gmail_thread_id ON emails (gmail_thread_id);

-- ----------------------------------------------------------------------------
-- actions
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT/UPDATE in src/routes/actions/+page.server.ts
-- and src/routes/contacts/[id]/+page.server.ts (add_action/update_action).
CREATE TABLE actions (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Nullable: actions/+page.server.ts create action allows `d.get('contact_id') || null`.
  contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
  titel      text NOT NULL,
  status     action_status NOT NULL DEFAULT 'offen',
  -- GUESS: modeled as DATE ("faellig am" = due date, always NULLS LAST ordering, no
  -- time-of-day usage observed) — could plausibly be timestamptz instead.
  faellig_am date,
  notizen    text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_actions_contact_id ON actions (contact_id);
CREATE INDEX idx_actions_status_faellig_am ON actions (status, faellig_am);

-- ----------------------------------------------------------------------------
-- prospects
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT/UPDATE column lists in:
--   src/routes/prospects/+page.server.ts (create/update/import_csv)
--   src/routes/api/v1/prospects/+server.ts (POST — also confirms sperre/sperre_grund)
-- and src/lib/types.ts `Prospect`.
CREATE TABLE prospects (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text NOT NULL,
  vorname      text,
  nachname     text,
  titel        text,
  -- GUESS: same caveat as contacts.anrede — TS restricts to 'Herr'|'Frau'|null but no
  -- DB-level enforcement observed; modeled as TEXT.
  anrede       text,
  email        text,
  firma        text,
  company_id   uuid REFERENCES companies(id) ON DELETE SET NULL,
  rolle        text,
  telefon      text,
  website      text,
  notizen      text,
  -- Nullable despite the ENUM: api/v1/prospects/+server.ts POST inserts an explicit
  -- NULL (`(body.status as string) || null`), so a NOT NULL constraint would break it.
  -- Default 'gesendet' matches the fallback used in the page-level create/update actions.
  status       prospect_status DEFAULT 'gesendet',
  kanal        text DEFAULT 'email', -- create action fallback: `d.get('kanal') || 'email'`
  -- GUESS: versandt_am/followup_am modeled as DATE — only ever ORDER BY'd (NULLS LAST),
  -- never compared with date-math; could plausibly be timestamptz.
  versandt_am  date,
  followup_am  date,
  sperre       boolean, -- api/v1/prospects/+server.ts: `Boolean(body.sperre)` or null
  sperre_grund text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- import_csv uses `ON CONFLICT DO NOTHING` with no explicit conflict target, which
-- Postgres only accepts if there's exactly one unique/exclusion constraint (or the
-- statement fails at runtime) — OR the table has none and this simply never conflicts
-- in practice (most likely, since no UNIQUE column is otherwise evidenced here).
-- GUESS: left without an extra UNIQUE constraint; flagged because the ON CONFLICT
-- clause in prospects/+page.server.ts:import_csv is otherwise inexplicable.
CREATE INDEX idx_prospects_company_id ON prospects (company_id);
CREATE INDEX idx_prospects_status ON prospects (status);
CREATE INDEX idx_prospects_versandt_am ON prospects (versandt_am);

-- ----------------------------------------------------------------------------
-- contact_files
-- ----------------------------------------------------------------------------
-- Columns confirmed via INSERT/SELECT in:
--   src/routes/api/contacts/[id]/files/+server.ts (GET/POST)
--   src/routes/api/contacts/[id]/files/[fid]/+server.ts (GET/DELETE)
CREATE TABLE contact_files (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  filename   text NOT NULL,
  mimetype   text NOT NULL,
  -- Stored as a base64 data: URL string (`data:${mimetype};base64,${base64}`), read
  -- back with `.split(',')[1]` — confirmed TEXT, not bytea.
  data       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_contact_files_contact_id ON contact_files (contact_id);

-- ----------------------------------------------------------------------------
-- VIEW: contact_timeline
-- ----------------------------------------------------------------------------
-- Reconstructed from src/lib/types.ts `TimelineEntry` (contact_id, art, eintrag_id,
-- subtyp, datum, titel, inhalt) plus usage in:
--   src/routes/+page.server.ts        — `(SELECT datum FROM contact_timeline WHERE contact_id = co.id ORDER BY datum DESC LIMIT 1)`
--   src/routes/contacts/[id]/+page.server.ts — `SELECT * FROM contact_timeline WHERE contact_id = ${params.id} ORDER BY datum DESC`
--   src/lib/components/TimelineItem.svelte    — reads entry.art/subtyp/datum/titel/inhalt/eintrag_id
-- art discriminates 'interaction' vs 'email'; subtyp carries interactions.typ or
-- emails.richtung respectively (used as icon-map keys); titel/inhalt map to
-- zusammenfassung/text (interactions) or betreff/body_text (emails) — confirmed by
-- TimelineItem.svelte's edit form field names (`zusammenfassung`/`text` vs
-- `betreff`/`body_text`).
CREATE VIEW contact_timeline AS
  SELECT
    contact_id,
    'interaction'::text AS art,
    id                  AS eintrag_id,
    typ::text           AS subtyp,
    datum,
    zusammenfassung     AS titel,
    text                AS inhalt
  FROM interactions
  UNION ALL
  SELECT
    contact_id,
    'email'::text AS art,
    id            AS eintrag_id,
    richtung::text AS subtyp,
    datum,
    betreff       AS titel,
    body_text     AS inhalt
  FROM emails;

-- ============================================================================
-- END OF RECONSTRUCTED SCHEMA
-- ============================================================================
